{{- if .Values.agent.enabled -}}

apiVersion: apps/v1
kind: {{ .Values.agent.kind }}
metadata:
  name: {{ include "netbird.fullname" . }}-agent
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.agent.labels" . | nindent 4 }}
  {{- with .Values.agent.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if eq .Values.agent.kind "Deployment" }}
  replicas: {{ .Values.agent.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "netbird.agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.agent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "netbird.agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.agent.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "netbird.agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-agent
          securityContext:
            {{- toYaml .Values.agent.securityContext | nindent 12 }}
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          {{- if or (.Values.agent.env) (.Values.agent.envRaw) (.Values.agent.envFromSecret) }}
          env:
          {{- range $key, $val := .Values.agent.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- if .Values.agent.envRaw }}
            {{- with .Values.agent.envRaw }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- range $key, $val := .Values.agent.envFromSecret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ (split "/" $val)._0 }}
                  key: {{ (split "/" $val)._1 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          {{- if .Values.agent.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.agent.volumeMounts | nindent 12 }}
          {{- end }}
      {{- if .Values.agent.volumes }}
      volumes:
        {{- toYaml .Values.agent.volumes | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
